# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_DAEM:     ROLE_DAEM
        ROLE_POSTULANT:     ROLE_POSTULANT
        ROLE_DEVELOPER:   [ROLE_ADMIN, ROLE_DAEM, ROLE_POSTULANT]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: daem_cv_default_panel
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/monitor/, role: ROLE_DAEM }
        - { path: ^/teacher/, role: ROLE_TEACHER }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/panel, role: [ROLE_ADMIN, ROLE_DAEM, ROLE_POSTULANT,ROLE_DEVELOPER]}
